### ISSUE TITLE
Support citing IETF documents according to IETF official guidance

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-render#28]
In a discussion with IETF and the IAB we have agreed on the following citation guidance that complies with ISO 690:
https://github.com/relaton/relaton-ietf/issues/98

Once Relaton-IETF is updated, relaton-render can implement rendering rules to utilize this information.

**Comment by opoudjis** [comment]
Blocked by https://github.com/relaton/relaton-ietf/issues/98

**Comment by opoudjis** [comment]
I will remove publisher as well in IETF rendering. 

> This went wrong for us - publisher is not really welcome here - see https://github.com/ietf-tools/bibxml-service/issues/321

Liaise with Andrej.

**Comment by opoudjis** [comment]
@ronaldtse This issue is misconceived.

metanorma-ietf generates RFC XML 3.

References in RFC XML 3 are constrained to contain the following non-deprecated, semantically populated elements, https://datatracker.ietf.org/doc/html/rfc7991#section-2.40

* `@target`: URI
* front/title
* front/seriesInfo (with specific settings for IETF documents)
* front/author
* front/date
* annotation: text trailing reference proper
* refcontent: text between title and date

We're already populating this structure; e.g.

````
    <references anchor="_informative_references">
      <name>Informative references</name>
      <reference target="https://www.rfc-editor.org/info/rfc8128" anchor="iet1">
        <front>
          <title>IETF Appointment Procedures for the ICANN Root Zone Evolution Review Committee</title>
          <author fullname="C. Morgan" asciiFullname="C. Morgan"></author>
          <date month="March" year="2017"></date>
        </front>
        <format target="https://www.rfc-editor.org/info/rfc8128" type="src"></format>
        <refcontent>RFC 8128</refcontent>
        <seriesInfo value="8128" name="RFC"></seriesInfo>
        <seriesInfo value="10.17487/RFC8128" name="DOI"></seriesInfo>
      </reference>
      <reference target="https://www.rfc-editor.org/info/rfc8216" anchor="iet2">
        <front>
          <title>HTTP Live Streaming</title>
          <author fullname="R. Pantos" asciiFullname="R. Pantos" role="editor"></author>
          <author fullname="W. May" asciiFullname="W. May"></author>
          <date month="August" year="2017"></date>
          <keyword>HTML</keyword>
          <keyword>streaming</keyword>
          <keyword>media</keyword>
        </front>
        <format target="https://www.rfc-editor.org/info/rfc8216" type="src"></format>
        <refcontent>RFC 8216</refcontent>
        <seriesInfo value="8216" name="RFC"></seriesInfo>
        <seriesInfo value="10.17487/RFC8216" name="DOI"></seriesInfo>
      </reference>
      <reference anchor="iet3">
        <front>
          <title>The ARK Identifier Scheme</title>
          <author fullname="John A. Kunze" asciiFullname="John A. Kunze"></author>
          <author fullname="Emmanuelle Bermès" asciiFullname="Emmanuelle Bermes"></author>
          <date month="June" year="2019"></date>
        </front>
        <format target="https://www.ietf.org/archive/id/draft-kunze-ark-22.txt" type="TXT"></format>
        <refcontent>Internet-Draft draft-kunze-ark-22</refcontent>
        <seriesInfo value="kunze-ark" name="Internet-Draft"></seriesInfo>
      </reference>
      <reference anchor="iet4">
        <front>
          <title>The ARK Identifier Scheme</title><author surname="Unknown"></author>
        </front>
        <refcontent>Internet-Draft draft-kunze-ark</refcontent>
      </reference>
    </references>
````

https://github.com/relaton/relaton-ietf/issues/98 is prescribing a particular rendering. That's nice, but RFC XML does not do anything with rendering, it does not do anything with standards bodies or publishers, and there are real limits to what we can do with refcontent. (Besides which, the prescribed rendering is inconsistent with the presupposed rendering of RFC XML.)

Rendering citations is the business of rfc2xml, not Metanorma: RFC XML encodes strictly semantics in citations. Unless RFC XML has been completely reengineered (and I'm seeing no indication of it in https://datatracker.ietf.org/doc/html/draft-levkowetz-xml2rfc-v3-implementation-notes-13 ), there is nothing for me to do with relaton-render in metanorma-ietf.

What am I missing here? What did IETF expect to happen in RFC XML as  a result of https://github.com/relaton/relaton-ietf/issues/98 ?

**Comment by opoudjis** [comment]
We have introduced authorizers as contributors to surface SDOs separately from publishers, and changed relaton-ietf output. That means we are able to satisfy IETF's desire to represent their references in other SDOs more accurately—though still at the discretion of their actual styling.
